import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Banner from '../components/Banner';
import About from '../components/About';
import ProjectList from '../components/ProjectList';
import Gallery from '../components/Gallery';
import Skills from '../components/Skills';
import Footer from '../components/Footer';
import Logo from '/public/images/collider_logo.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='py-8 font-mono text-slate-700'>
        <Header />
        <Banner />
        <About />
        <ProjectList />
        <Gallery />
        <Skills />
        <Footer />
      </main>
    </>
  );
}
